#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - 6.9.2

#运行的脚本命令
script:
  - npm run test

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgif-dev